title: SOOQLINK Documentation
description: B2B Marketplace Platform for Algeria
theme: jekyll-theme-cayman
baseurl: "/SOOQLINK"
url: "https://imenmzg.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md

